name: CI/CD pipeline for opening a pull request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Running OpenAPI Spec diff action
        uses: oasdiff/oasdiff-action/breaking@main
        with:
          # In original actions we would use this base:
          # https://raw.githubusercontent.com/APIprotector/demo/refs/heads/master/src/main/resources/openapi.yaml

          # And we would use this revision (new api spec) from the current changes coming up from pull request
          # https://raw.githubusercontent.com/APIprotector/demo/refs/heads${{ github.ref_name }}/src/main/resources/openapi.yaml
          base: https://raw.githubusercontent.com/APIprotector/ApiSpecRetriever/refs/heads/master/API%20Specki/Kubernetes/swagger_2025-03-25.json
          revision: https://raw.githubusercontent.com/APIprotector/ApiSpecRetriever/refs/heads/master/API%20Specki/Kubernetes/swagger_2025-03-25.json
          fail-on: ERR
          include-path-params: false
          composed: false

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          cache: 'maven'
          distribution: 'corretto'

      - name: Add executable permissions
        run: chmod a+x mvnw
        
      - name: Maven install dependencies
        run: ./mvnw clean install package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-protector
          path: ./target/*.jar
